# Generated by Django 4.0.3 on 2022-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante', models.CharField(max_length=50, verbose_name='Representante')),
                ('rubro', models.CharField(max_length=50, verbose_name='Rubro')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100, verbose_name='Entidad')),
                ('impuesto', models.CharField(max_length=100, verbose_name='impuesto')),
                ('observacion', models.CharField(max_length=100, verbose_name='Observación')),
                ('n_comprobante', models.IntegerField(verbose_name='Numero comprobante')),
                ('fecha', models.DateField(verbose_name='Fecha vencimiento')),
            ],
        ),
    ]
