# Generated by Django 4.0.3 on 2022-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioImpuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos',
            name='impuesto',
            field=models.CharField(max_length=100, verbose_name='Impuesto'),
        ),
    ]
